### ISSUE TITLE
사용자 Entity 구성

### ISSUE THREAD

**Issue by leesj8116** [9o-clock/9o-clock-server#15]

**Comment by leesj8116** [comment]
# 작업 내용
## `Member` 테이블 구성
JPA를 활용하여, 사용자 관리에 필요한 Member 테이블 구축 (User 테이블명이 문제가 되어, member로 변경)
### 테이블 구성간 확인 필요 사항
- id 관리 : Long을 이용한 augo generated를 사용할까? 아니면 UUID를 활용할까
- 중복 닉네임 관리 : 중복된 닉네임을 허용할 것인가?
- 닉네임의 한글 관리 : 닉네임에서 한글을 허용할 것인가?

**Comment by PCloud63514** [comment]
User 테이블 명이 어떤 문제가 있었나요?

**Comment by leesj8116** [comment]
![image](https://user-images.githubusercontent.com/105261571/227078766-30e1338b-e3e7-44f5-b3d3-2c33e20f85d5.png)

[user가 h2에서 예약어로 되어 있어](https://velog.io/@readnthink/DataJpaTest사용시-user-table-예약어-에러) 이름을 `Member`로 변경했습니다.

사실 작업하면서는 그냥 이름을 바꾸자! 라고 접근했는데, 상의한 부분이 아니긴 합니다.
그래서 `Users`로 테이블 명을 바꾸거나 `NON_KEYWORDS=USER`를 붙여 해결해도 될 듯 합니다.

**Comment by PCloud63514** [comment]
회원가입의 기능이 있다보니 Member가 알맞을 것 같습니다.
메신저에서 해당 내용은 한 번 공유 부탁드려요~

**Comment by leesj8116** [comment]
우선 `Member`가 적절하지 않다는 의미는 이해했습니다.
작업중인 브런치에는 `@Table(name = "users")`로 수정하여 일단 반영하겠습니다.
토의 후 결정되는 방향으로 수정하겠습니다!
